version: "3.3"
services:
  garden:
    build: .
    links:
      - mongodb:mongodb
    volumes:
      - .:/usr/src/garden
    expose:
      - "3031"
    environment:
      - APP_CONFIG=config.production
    command: uwsgi --yml uwsgi.yml
    tty: true
  nginx:
    image: nginx:latest
    links:
      - garden:uwsgi
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"