version: "3.3"
services:
  garden:
    image: python:latest
    links:
      - mongodb:mongodb
    volumes:
      - .:/usr/src/garden
    expose:
      - "3031"
    tty: true
  nginx:
    image: nginx:latest
    links:
      - garden:uwsgi
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  mongodb:
    image: mongo:latest
    expose:
      - "27017"